// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	documentstore "github.com/Nick2603/golang/lesson_06/documentstore"
	mock "github.com/stretchr/testify/mock"
)

// CollectionStore is an autogenerated mock type for the CollectionStore type
type CollectionStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *CollectionStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *CollectionStore) Get(id string) (*documentstore.Document, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *documentstore.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*documentstore.Document, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *documentstore.Document); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*documentstore.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *CollectionStore) List() []documentstore.Document {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []documentstore.Document
	if rf, ok := ret.Get(0).(func() []documentstore.Document); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]documentstore.Document)
		}
	}

	return r0
}

// Put provides a mock function with given fields: doc
func (_m *CollectionStore) Put(doc documentstore.Document) error {
	ret := _m.Called(doc)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(documentstore.Document) error); ok {
		r0 = rf(doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCollectionStore creates a new instance of CollectionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectionStore {
	mock := &CollectionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
